### PR TITLE
fix: resolve dev server hot options correctly

### LINKED ISSUE #2004: [serve] --hot-only is broken
**Describe the bug**

`--hot-only` is broken.

**What is the current behavior?**

Screenshot at 2020-10-31 16-39-01

**To Reproduce**

`webpack serve --hot-only`

**Expected behavior**

Should work properly.

**Screenshots**
pasted above

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
No

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Need update 

**Summary**
- Fix how `hot` flag is resolved in serve package

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes #2004

### CODE REVIEW

File: packages/serve/src/createConfig.ts [hunk 1]
```diff
@@ -1,4 +1,8 @@
 import { devServerOptionsType } from './types';
+// eslint-disable-next-line node/no-extraneous-import
+import { version } from 'webpack-dev-server/package.json';
```
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:3]: We should use `packageExist` or use `try`/`catch`

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:3]: yep on it

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:3]: handled at the entry of serve package to avoid redundant checks

File: packages/serve/src/createConfig.ts [hunk 2]
```diff
@@ -18,11 +22,17 @@ export default function createConfig(args): devServerOptionsType {
...
-        delete options.hotOnly;
+    if (isDevServer4) {
+        if (options.hotOnly) {
+            options.hot = 'only';
+            // hotOnly is not a valid devServer option
+            delete options.hotOnly;
+        }
+    } else {
+        // only apply hotOnly when both are supplied
+        if (options.hot && options.hotOnly) {
```
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:33]: It will break `hot` ability, why we need delete it?

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:33]: should we allow setting both hot and hotOnly?

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:33]: won't that apply the plugin twice?

File: packages/serve/src/createConfig.ts [hunk 3]
```diff
@@ -18,11 +22,17 @@ export default function createConfig(args): devServerOptionsType {
...
-        // hotOnly is not a valid devServer option
-        delete options.hotOnly;
+    if (isDevServer4) {
+        if (options.hotOnly) {
+            options.hot = 'only';
+            // hotOnly is not a valid devServer option
+            delete options.hotOnly;
+        }
+    } else {
+        // only apply hotOnly when both are supplied
```
Comment (anshumanv) [inline packages/serve/src/createConfig.ts:32]:
```suggestion
        // when both hot flags are supplied, only hotOnly is applied
```

File: packages/serve/src/createConfig.ts (hunk 2 above)
Comment (evilebottnawi) [reply packages/serve/src/createConfig.ts:33]: hm, I think you are right here, we should not apply plugin twice, but we have logic on webpack-dev-server side (if you have plugin we don't add it again), removing hot is not safe, because we adding client code for HMR when hot is true

File: packages/serve/src/createConfig.ts (hunk 3 above)
Comment (snitin315) [reply packages/serve/src/createConfig.ts:32]: `prefer --hotOnly over --hot`

File: packages/serve/src/createConfig.ts (hunk 2 above)
Comment (anshumanv) [reply packages/serve/src/createConfig.ts:33]: ah okay then we can remove this

File: packages/serve/src/createConfig.ts (hunk 3 above)
Comment (anshumanv) [reply packages/serve/src/createConfig.ts:32]: server seems to have logic for this so this is not needed anymore

File: packages/serve/src/createConfig.ts [hunk 4]
```diff
@@ -18,8 +22,7 @@ export default function createConfig(args): devServerOptionsType {
         // clientLogging is not a valid devServer option
         delete options.clientLogging;
     }
-
-    if (options.hotOnly) {
+    if (isDevServer4 && options.hotOnly) {
```
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:25]: I think we don't have `options.hotOnly` on CLI only `hot` and `hot = 'only'`

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:25]: we have it on v3

Comment (evilebottnawi) [reply packages/serve/src/createConfig.ts:25]: But options from webpack-cli

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:25]: nope options here is the dev server flags

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:25]: printed and checked 😄

File: packages/serve/src/createConfig.ts (hunk 1 above)
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:3]: Still can be error, I don't think we should use `import`/`require` on the top of files for peer dependencies, I think we don't have a problem here, because we check it before, but better do not do it, because we can refactoring something and break code

File: packages/serve/src/createConfig.ts (hunk 4 above)
Comment (evilebottnawi) [reply packages/serve/src/createConfig.ts:25]: thanks

File: packages/serve/src/createConfig.ts (hunk 1 above)
Comment (anshumanv) [reply packages/serve/src/createConfig.ts:3]: agree, changing 👍

File: packages/serve/src/createConfig.ts [hunk 5]
```diff
@@ -14,6 +10,10 @@ const isDevServer4 = version.startsWith('4');
  */
 export default function createConfig(args): devServerOptionsType {
     const options = { ...args };
+    // eslint-disable-next-line node/no-extraneous-require
+    const version = require('webpack-dev-server/package.json').version;
```
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:14]: And let's use `try`/`catch`, because any `require` can throw and error

File: packages/serve/src/createConfig.ts [hunk 6]
```diff
@@ -10,6 +10,15 @@ import { devServerOptionsType } from './types';
  */
 export default function createConfig(args): devServerOptionsType {
     const options = { ...args };
+    let isDevServer4 = false;
+    try {
+        // eslint-disable-next-line node/no-extraneous-require
+        const version = require('webpack-dev-server/package.json').version;
+
+        isDevServer4 = version.startsWith('4');
```
Comment (evilebottnawi) [inline packages/serve/src/createConfig.ts:18]: Let's move out it from `try`/`catch`, because it is unnecessary have here

Comment (anshumanv) [reply packages/serve/src/createConfig.ts]: done

**Review by evilebottnawi — COMMENTED** [review]
Can we add simple test for `webpack --hot` and `webpack-hot=only` to avoid problems in future

File: packages/serve/src/createConfig.ts [hunk 7]
```diff
@@ -10,6 +10,15 @@ import { devServerOptionsType } from './types';
  */
 export default function createConfig(args): devServerOptionsType {
     const options = { ...args };
+    let isDevServer4 = false,
```
Comment (rishabh3112) [inline packages/serve/src/createConfig.ts:13]: Let's keep `webpack-dev-server` check in a single place.
It is in `index.ts` as well as this file.

**Review by rishabh3112 — CHANGES_REQUESTED** [review]
Left a suggestion. Rest looks good to me 😃

File: packages/serve/src/createConfig.ts (hunk 7 above)
Comment (anshumanv) [reply packages/serve/src/createConfig.ts:13]: @evilebottnawi suggested to keep it here too

Comment (rishabh3112) [reply packages/serve/src/createConfig.ts:13]: When availability of `webpack-dev-server` is already tested in `index.ts` which is entry file to `serve` package, why do we need to test it again?

Comment (anshumanv) [reply packages/serve/src/createConfig.ts:13]: https://github.com/webpack/webpack-cli/pull/2022#discussion_r516001135

**Comment by anshumanv** [comment]
> Can we add simple test for webpack serve --hot and webpack serve --hot=only to avoid problems in future


We already have tests for those flags, also updated the tests for createConfig which was causing this problem

File: packages/serve/src/createConfig.ts (hunk 7 above)
Comment (rishabh3112) [reply packages/serve/src/createConfig.ts:13]: Okay, lets keep it then.

File: packages/serve/src/parseArgs.ts [hunk 8]
```diff
@@ -23,13 +23,8 @@ type ArgsType = {
...
 export default function parseArgs(cli: WebpackCLIType, args: string[]): ArgsType {
-    let devServerFlags: object[];
-    try {
-        // eslint-disable-next-line node/no-extraneous-require
-        devServerFlags = require('webpack-dev-server/bin/cli-flags').devServer;
-    } catch (err) {
-        throw new Error(`You need to install 'webpack-dev-server' for running 'webpack serve'.\n${err}`);
-    }
+    // eslint-disable-next-line node/no-extraneous-require
+    const devServerFlags = require('webpack-dev-server/bin/cli-flags').devServer;
```
Comment (rishabh3112) [inline packages/serve/src/parseArgs.ts:27]: Same logic goes here too, error can occur here as well if dev server changes files.

Comment (evilebottnawi) [reply packages/serve/src/parseArgs.ts:27]: Yes, you are right

Comment (anshumanv) [reply packages/serve/src/parseArgs.ts]: done

**Review by snitin315 — CHANGES_REQUESTED** [review]
Need a rebase

**Comment by anshumanv** [comment]
rebase done

**Review by evilebottnawi — APPROVED** [review]

File: packages/serve/src/index.ts [hunk 9]
```diff
@@ -10,6 +10,12 @@ import parseArgs from './parseArgs';
  * @returns {Function} invokes the devServer API
  */
 export default function serve(...args: string[]): void {
+    try {
+        // eslint-disable-next-line node/no-extraneous-require
+        require('webpack-dev-server');
+    } catch (err) {
+        throw new Error(`You need to install 'webpack-dev-server' for running 'webpack serve'.\n${err}`);
+    }
```
Comment (snitin315) [inline packages/serve/src/index.ts:18]: exitCode ?

Comment (evilebottnawi) [reply packages/serve/src/index.ts:18]: /cc @anshumanv

Comment (anshumanv) [reply packages/serve/src/index.ts:18]: exit code is missing in all tests, we'll have to change utils to export it, future PR

Comment (evilebottnawi) [reply packages/serve/src/index.ts:18]: I think we should use `process.exit(2)` here to avoid problems

Comment (anshumanv) [reply packages/serve/src/index.ts:18]: throwing err will exit the process, doing process.exit() after throw would be unreachable code

Comment (evilebottnawi) [reply packages/serve/src/index.ts:18]: So let's use `logger.error(); process.exit(2)`, because throw will be use `1` exit code, but `1` exit code only for webpack bundle problems

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team 

Will be great to add more tests, but let's focus on coverage in other PRs

**Review by snitin315 — APPROVED** [review]

**Review by rishabh3112 — APPROVED** [review]
