### PR TITLE
fix: cli-executer supplies args further up

### LINKED ISSUE #1901: cli executer fails to invoke runCLI()
**Describe the bug**
#1255 brought a better way to handle unknown flags by showing up the available options and asking the user to pick what they required. Everything works well except that it fails to supply the chosen args further up.

**What is the current behavior?**
`cli-executer` won't supply the chosen args since it fails to recognize `runCLI()` as a function.

Screenshot 2020-10-10 at 12 23 31 AM

**To Reproduce**

An interactive prompt shows up with all of the available `cli-flags` if the user makes a typo.
Say, `webpack-cli --entyr ./a.js`

Choose `--entry` and supply `./a.js` as the value. Notice that an error message shows up. (screenshot is given below)

**Expected behavior**
`cli-executer` supplies the chosen args to `runCLI()`.

**Screenshots**

Screenshot 2020-10-10 at 12 13 47 AM

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

https://github.com/webpack/webpack-cli/blob/c0eb2801e32bb1b297a4bf21f9cc6dfbe7a12c83/packages/webpack-cli/lib/bootstrap.js#L59

https://github.com/webpack/webpack-cli/blob/c0eb2801e32bb1b297a4bf21f9cc6dfbe7a12c83/packages/webpack-cli/lib/utils/cli-executer.js#L58

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
Updated existing tests.

**If relevant, did you update the documentation?**
N/A

**Summary**
closes #1901 

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

File: packages/webpack-cli/lib/utils/cli-executer.js [hunk 1]
```diff
@@ -49,16 +48,17 @@ async function prompter() {
...
+const run = async () => {
     try {
         const args = await prompter();
         logger.info('\nExecuting CLI\n');
-        await runCLI(args);
+        return args;
     } catch (err) {
-        logger.error(`Action Interrupted, use ${cyan('webpack-cli help')} to see possible options.`);
+        logger.error(`${err} Action Interrupted, use ${cyan('webpack-cli help')} to see possible options.`);
+        process.exit(1);
```
Comment (snitin315) [inline packages/webpack-cli/lib/utils/cli-executer.js:60]:
```suggestion
        process.exit(2);
```

**Review by anshumanv — APPROVED** [review]

File: packages/webpack-cli/lib/utils/cli-executer.js [hunk 2]
```diff
@@ -49,16 +48,17 @@ async function prompter() {
...
-async function run() {
+const run = async () => {
     try {
         const args = await prompter();
         logger.info('\nExecuting CLI\n');
-        await runCLI(args);
+        return args;
     } catch (err) {
         logger.error(`Action Interrupted, use ${cyan('webpack-cli help')} to see possible options.`);
+        process.exit(2);
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/utils/cli-executer.js:60]: @webpack/cli-team we need tests this, let's do it in separate PR, because we need do release today
