### PR TITLE
fix: close compiler, own sh script and output clearing

### LINKED ISSUE #737: Json parameter includes console.log output
# Bug report

**What is the current behavior?**
If you try watching webpack with profiler and json output then you'll get a corrupted json file, that includes webpack's console.log output.

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute `webpack --watch --progress --profile --json > stats.json` and get this in your json file:

```
webpack is watching the files…
```

**What is the expected behavior?**
Json parameter should filter out console.log output from the json file.

I am using webpack 4 (can be reproduced on any version).

---

This issue was moved from webpack/webpack#8647 by @ooflorent. Original issue was by @CyberAP.

### PR DESCRIPTION
**Pull request by evenstensberg**
**What kind of change does this PR introduce?**
Fixes #737  #743 and #739 

**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**
N/A
**Summary**

Emits logs to stderr, adds own bash script for opencollective to reduce library size and closes compiler to purge cache in webpack v5.

**Does this PR introduce a breaking change?**
No

**Other information**
:)

### CODE REVIEW

**Comment by evenstensberg** [comment]
We probably need to update tests, cause we emit to stderr now

File: bin/cli.js [hunk 1]
```diff
@@ -491,8 +487,12 @@ For more information, see https://webpack.js.org/api/cli/.`);
 					process.stdin.resume();
 				}
 				compiler.watch(watchOptions, compilerCallback);
-				if (outputOptions.infoVerbosity !== "none") console.log("\nwebpack is watching the files…\n");
-			} else compiler.run(compilerCallback);
+				if (outputOptions.infoVerbosity !== "none") console.error("\nwebpack is watching the files…\n");
+				if (compiler.close) compiler.close(compilerCallback);
```
Comment (PlayMa256) [inline bin/cli.js]: Why not add 491 and 494 outside of the if statement into its own branch? (be sibling of `if(firstOptions.watch...`)

**Comment by evenstensberg** [comment]
Multi env tests in azure is fixed
