### PR TITLE
fix: show warning if bail and watch are used together

### LINKED ISSUE #1794: bail = true should not kill watch mode on ModuleNotFound error
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When `bail = true`, a ModuleNotFound error during a change of the files will cause the entire watch process to either abort or get stuck. Subsequent rebuilds will not happen even if the file changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

* run webpack in watch mode
* add `import './non-existant-module'` to any file
* webpack rebuild fails or exits
* remove the import
* rebuild is not triggered either due to webpack exit (3.10 and below) or due to hang (3.11)

node version: 8.9.4

Webpack 3.11 made one step towards fixing this with https://github.com/webpack/webpack/pull/5797

However even though the process does not die, rebuilds stop happening.

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
maybe fix

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
No
**Summary**
Fixes #1794 

 show a warning if `bail` and `watch` are used together with either config or as cli args.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

File: packages/webpack-cli/lib/bootstrap.js [hunk 1]
```diff
@@ -71,6 +71,10 @@ async function runCLI(cliArgs) {
             parsedArgsOpts.entry = entry;
         }
 
+        if (parsedArgsOpts.bail && parsedArgsOpts.watch) {
+            logger.warn('You are using "bail" with "watch". "bail" will still exit webpack when the first error is found.');
+        }
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/bootstrap.js:76]: We should look at `compiler.options.bail` and `parsedArgsOpts.watch`, because other plugins can change options

File: packages/webpack-cli/lib/groups/ConfigGroup.js [hunk 2]
```diff
@@ -127,6 +127,11 @@ class ConfigGroup extends GroupHelper {
             newOptionsObject['options'] = configOptions;
         }
 
+        //warn the user if bail and watch both are used together
+        if (configOptions.bail && configOptions.watch) {
+            logger.warn('You are using "bail" with "watch". "bail" will still exit webpack when the first error is found.');
+        }
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/groups/ConfigGroup.js:133]: Ideally we should only one place for this, no need t duplicate code

File: packages/webpack-cli/lib/utils/Compiler.js [hunk 3]
```diff
@@ -118,7 +118,7 @@ class Compiler {
         }
 
         //warn the user if bail and watch both are used together
-        if (this.compiler.options.bail && outputOptions.watch) {
+        if (this.compiler.options.bail && (outputOptions.watch || options.watch)) {
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/utils/Compiler.js:121]: `this.compiler.options.bail && this.compiler.watchMode`

File: packages/webpack-cli/lib/utils/Compiler.js [hunk 4]
```diff
@@ -117,6 +117,11 @@ class Compiler {
             return interactive(options, outputOptions);
         }
 
+        //warn the user if bail and watch both are used together
+        if (!this.compiler.compilers && this.compiler.options.bail && this.compiler.watch) {
+            logger.warn('You are using "bail" with "watch". "bail" will still exit webpack when the first error is found.');
+        }
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/utils/Compiler.js:123]: `this.compiler` can be array when you use multi compiler mode, we need handle this

File: packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js [hunk 5]
```diff
@@ -0,0 +1,7 @@
+const logger = require('../logger');
+
+module.exports = (compiler) => {
+    if (compiler.options.bail && compiler.watch) {
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: Looks good, but why we don't use `compiler.watchMode`?

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: Don't know why but it isn't working with `compiler.watchMode`.

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L336 is always `true`, we need to use `watchMode`, can you try it again?

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: Not working. I logged `compiler` in the console and found `watchMode: false` instead 😕 , 

screenshot-github-com-webpack-webpack-cli-pull-1804-1600434195860

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: oh, yes, I was wrong, `watchMode` is true only when we run `compiler.watch()`, so we need use `watch`

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: Maybe we should use `compiler.options.watch`?

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: with `compiler.options.watch` the process exits too soon without printing the warning in case an error is found.

Screenshot at 2020-09-18 18-54-11

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: We need to search way to detect watch mode, because `compiler.watch` is method and it is always true

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: Ah yes, then we have `compiler.options.bail && (outputOptions.watch || options.watch)`

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: `outputOptions.watch` is `true` when we run `compiler.watch`

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:4]: > `compiler.options.bail && (outputOptions.watch || compiler.options.watch)` 

`outputOptions,watch` is true when we pass `--watch` via `CLI`, so we need to check the existence of `outputOptions.watch` else `webpack --bail --watch` will not log the warning. The rest of all cases will log the warning.

Comment (snitin315) [reply packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js]: Fixed, the issue was with `--watch` flag it was not setting `compiler.options.watch` equal to `true`. Now works perfect.

Screenshot at 2020-09-19 15-37-23

File: test/bail/bail-and-watch-warning.test.js [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+        expect(stdout).toBeTruthy();
+    });
+
+    it('should log warning in case of multiple compilers', () => {
+        const { stderr, stdout } = run(__dirname, ['-c', 'multi-webpack.config.js']);
+
+        expect(stderr).toContain(`You are using "bail" with "watch". "bail" will still exit webpack when the first error is found.`);
+        expect(stdout).toBeTruthy();
+    });
+});
```
Comment (evilebottnawi) [inline test/bail/bail-and-watch-warning.test.js:19]: Can we add tests where `bail: false` and `watch: true`/`watch: false` and `bail: true` and check there is not warnings/errors?

Comment (snitin315) [reply test/bail/bail-and-watch-warning.test.js:26]: Added

**Review by evenstensberg — DISMISSED** [review]

File: packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js [hunk 7]
```diff
@@ -0,0 +1,7 @@
+const logger = require('../logger');
+
+module.exports = (compiler) => {
```
Comment (rishabh3112) [inline packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js:3]: Assign this to variable and then assign it to `module.exports`.
Add a comment about function(or file) as well.

**Review by rishabh3112 — DISMISSED** [review]
Left a small suggestion.
Rest looks good to me.

**Review by evenstensberg — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]

**Review by jamesgeorge007 — APPROVED** [review]
