### PR TITLE
cli(bugfix): Allow mode "none" in CLI

### LINKED ISSUE #378: Webpack examples
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

- missing module: uri-js
- Argument: mode, Given: "none", Choices: "development", "production"

**If the current behavior is a bug, please provide the steps to reproduce.**

In order to run the webpack examples I need to link webpack-cli.
```
git clone ..webpack-cli
yarn install
yarn link
```

```
cd local/webpack/repo
yarn link webpack-cli
yarn build:examples  --> missing module `uri-js`
```

**webpack-cli repo**^
Have to install `uri-js` to make it work.
`yarn add uri-js --dev`

**webpack-repo**
`yarn build:examples`
Build runs and fails at example `source-maps`:
`--> Argument: mode, Given: "none", Choices: "development", "production"`

[Referencing existing/merged PR](https://github.com/webpack/webpack-cli/pull/278)

**What is the expected behavior?**
Run the examples without any error.

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
webpack-cli 2.0.14
webpack "4.5.0",
Win10 x64^

```
 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  Binaries:
    Node: 8.10.0
    Yarn: 1.5.1
    npm: 5.8.0
  Browsers: {}
  npmPackages:
    i18n-webpack-plugin:
      wanted: ^1.0.0
      installed: 1.0.0
    uglifyjs-webpack-plugin:
      wanted: ^1.2.4
      installed: 1.2.4
    webpack-dev-middleware:
      wanted: ^1.9.0
      installed: 1.12.2
    webpack-sources:
      wanted: ^1.0.1
      installed: 1.1.0
  npmGlobalPackages:
    webpack-cli: 2.0.14
```

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Fixes #378 

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Adding `--mode none` to the `cli`

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

File: bin/config-yargs.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ module.exports = function(yargs) {
 			},
 			mode: {
 				type: "string",
-				choices: ["development", "production"],
+				choices: ["development", "production", "none"],
```
Comment (montogeek) [inline bin/config-yargs.js]: Can't these rules be imported from webpack repo, this is duplication, maybe using https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json

Comment (ematipico) [reply bin/config-yargs.js]: We definitely could, it actually makes sense, but I would improve it using a separate PR. Here I am just restoring something that we missed somehow... thanks for your feedback

Comment (montogeek) [reply bin/config-yargs.js]: Cool
