### PR TITLE
fix: set mode=production by default

### LINKED ISSUE #1678: Webpack default mode not set to production
# Bug report

As stated in https://webpack.js.org/configuration/mode/, "If not set, webpack sets production as the default value for mode."

**What is the current behavior?**
`argv` does not contain `mode` property set to `'production'`, when invoking `webpack` without any mode set.

**If the current behavior is a bug, please provide the steps to reproduce.**
file webpack.config.js:
``` 
module.exports = (env, argv) => { console.log(argv); }
```
now run `webpack`, without setting any mode, and see that the `argv` object logged does not contain `mode` property set to `'production'`.

**What is the expected behavior?**

`argv` object should have `mode` property set to `'production'`.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 14.3.0
Operating System: Mac OSX 10.15.5
Additional tools: None

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
NA
**Summary**
Resolve #1678 

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

File: packages/webpack-cli/lib/utils/cli-flags.js [hunk 1]
```diff
@@ -201,7 +201,7 @@ module.exports = {
             alias: 'p',
             usage: '--prod',
             type: Boolean,
-            defaultValue: undefined,
+            defaultValue: false,
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/utils/cli-flags.js:204]: I've always wondered why we have flags `--dev`/`--prod`, we already have `--mode`, it can be misleading for new developers and some of them will be write `webpack --prod --mode=production`, but it is wrong

Comment (snitin315) [reply packages/webpack-cli/lib/utils/cli-flags.js:204]: > I've always wondered why we have flags --dev/--prod, we already have --mode, it can be misleading for new developers and some of them will be write webpack --prod --mode=production, but it is wrong

It's just alias for `--mode=development or production` like we have `--verbose` for `--stats=verbose`. 
CLI throws a warning if user do something like `webpack --prod --mode=production` 
`You provided both 'mode' and --dev arguments. You should provide just one. "mode" will be used`

Comment (evilebottnawi) [reply packages/webpack-cli/lib/utils/cli-flags.js:204]: I think we should remove them in the future, but it is not high priority

Comment (snitin315) [reply packages/webpack-cli/lib/utils/cli-flags.js:204]: /cc @webpack/cli-team anyone in favor of `--dev` and `--prod`.? 
> Not a big deal but even if I understand the point of having clean and concise --dev and --prod options, I think the --mode= option better matches the way it works in configuration file and is more straightforward when you already know configuration file. Just my 2 cents, but I'm not sure a breaking change in this area is really useful ?

from feedback too https://github.com/webpack/webpack-cli/issues/1222#issuecomment-585678755
