### PR TITLE
fix: --config-name behaviour for fuctional configs

### LINKED ISSUE #1990: --config-name fails for a function returning an array of configurations
When `webpack.config.js` exports a function returning an array of named configurations, `webpack --config-name=NAME` can’t find them. It incorrectly complains `[webpack-cli] Configuration with name "NAME" was not found.`

```console
$ webpack --version

webpack-cli 4.1.0

webpack 5.3.0

$ cat >src.js <<EOF
console.log("Hello, world!")
EOF

$ cat >webpack.config.js <<EOF
module.exports = () => [
  { name: "a", output: { filename: "a.js" } },
  { name: "b", output: { filename: "b.js" } },
];

$ webpack 
[webpack-cli] Compilation finished
a:
  asset a.js 29 bytes [compared for emit] [minimized] (name: main)
  ./src.js 29 bytes [built] [code generated]
  a (webpack 5.3.0) compiled successfully in 147 ms

b:
  asset b.js 29 bytes [emitted] [minimized] (name: main)
  ./src.js 29 bytes [built] [code generated]
  b (webpack 5.3.0) compiled successfully in 139 ms

$ webpack --config-name=a
[webpack-cli] Configuration with name "a" was not found.
```

It works for a function returning a single configuration:

```console
$ cat >webpack.config.js <<EOF
module.exports = () => ({ name: "a", output: { filename: "a.js" } });
EOF

$ webpack --config-name=a
[webpack-cli] Compilation finished
asset a.js 29 bytes [compared for emit] [minimized] (name: main)
./src.js 29 bytes [built] [code generated]
a (webpack 5.3.0) compiled successfully in 157 ms
```

or for an array that’s not wrapped in a function:

```console
$ cat >webpack.config.js <<EOF
module.exports = [
  { name: "a", output: { filename: "a.js" } },
  { name: "b", output: { filename: "b.js" } },
];
EOF

$ webpack --config-name=a
[webpack-cli] Compilation finished
asset a.js 29 bytes [compared for emit] [minimized] (name: main)
./src.js 29 bytes [built] [code generated]
a (webpack 5.3.0) compiled successfully in 142 ms
```

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
No
**Summary**

Fixes #1990 

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 1]
```diff
@@ -204,7 +208,7 @@ const finalize = async (moduleObj, args) => {
         process.exit(2);
     }
 
-    newOptionsObject['options'] = isMultiCompilerMode ? configs : configs[0];
+    newOptionsObject['options'] = isMultiCompilerMode || isFunctionalConfig ? configs : configs[0];
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/groups/resolveConfig.js:211]: What if `Function` returns the one/multiple config(s)?

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:211]: Can you give an example?

Comment (evilebottnawi) [reply packages/webpack-cli/lib/groups/resolveConfig.js:211]:
```js
module.exports = () => {
  return { entry }
}
```

and

```js
module.exports = () => {
  return [{ entry }, { entry }]
}
```

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:211]: I will update PR with tests for both cases.

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 2]
```diff
@@ -176,8 +179,9 @@ const finalize = async (moduleObj, args) => {
 
     if (configName) {
         const foundConfigNames = [];
+        const configsToFilter = isFunctionalConfig ? configs[0] : configs;
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/groups/resolveConfig.js:182]: Can you clarify why we need logic here? `configs` already contains configurations, maybe I am missing something?

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:182]: It's needed when config returns an array of configs.

in that case, `configs` is -
```js
[
  [
    {
      output: [Object],
      name: 'first',
      entry: './src/first.js',
      mode: 'development',
      stats: 'minimal'
    },
    {
      output: [Object],
      name: 'second',
      entry: './src/second.js',
      mode: 'production',
      stats: 'minimal'
    }
  ]
]
```

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:182]: I think we need to update this logic as this happens only when an array of configs is returned.

Comment (evilebottnawi) [reply packages/webpack-cli/lib/groups/resolveConfig.js:182]: Weird, I think we should have `[config, config, config]` here

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:182]: hmm, I'm looking into it.

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 3]
```diff
@@ -179,7 +179,7 @@ const finalize = async (moduleObj, args) => {
 
     if (configName) {
         const foundConfigNames = [];
-        const configsToFilter = isFunctionalConfig ? configs[0] : configs;
+        const configsToFilter = Array.isArray[configs[0]] ? configs[0] : configs;
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/groups/resolveConfig.js:182]: I still think we have problems here, maybe `Array.isArray` need here

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 4]
```diff
@@ -166,6 +168,7 @@ const finalize = async (moduleObj, args) => {
 
             // `Promise` may return `Function`
             if (typeof rawConfig === 'function') {
+                isFunctionalConfig = true;
                 // when config is a function, pass the env from args to the config function
                 rawConfig = await rawConfig(env, args);
```
Comment (snitin315) [inline packages/webpack-cli/lib/groups/resolveConfig.js:173]: I think we need to map again if this returns an array.

Comment (evilebottnawi) [reply packages/webpack-cli/lib/groups/resolveConfig.js:173]: Do you mean when we return multiple configurations?

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:173]: Yes because when we have `module.exports = () => [config, config]` here it becomes `rawconfig = [ config, config ]` with which the next return statement becomes `[ [ config, config ] ]`.

Comment (evilebottnawi) [reply packages/webpack-cli/lib/groups/resolveConfig.js:173]: Let's refactor it, just put configuration in array

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:173]: Can you clarify?

Comment (evilebottnawi) [reply packages/webpack-cli/lib/groups/resolveConfig.js:173]:
```js
const result = [];

await Promise.all(() => { /* async code here */ }).map(item => result.push(item))
```

File: packages/webpack-cli/lib/groups/resolveConfig.js (hunk 3 above)
Comment (andersk) [reply packages/webpack-cli/lib/groups/resolveConfig.js:182]: If nothing else, the square brackets are a clear typo: `Array.isArray[…]` → `Array.isArray(…)`.

**Comment by snitin315** [comment]
Should be good now.

**Review by rishabh3112 — DISMISSED** [review]

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 5]
```diff
@@ -172,7 +174,15 @@ const finalize = async (moduleObj, args) => {
...
         }),
-    );
+    ).then((allConfigs) => {
+        allConfigs.map((singleConfig) => {
+            if (Array.isArray(singleConfig)) {
+                singleConfig.map((conf) => configs.push(conf));
+            } else {
+                configs.push(singleConfig);
+            }
+        });
```
Comment (andersk) [inline packages/webpack-cli/lib/groups/resolveConfig.js:184]: Nit: `map` shouldn’t be used for side effects; there’s `forEach` for that. But more simply,

```suggestion
        configs.push(...allConfigs.flat());
```

Comment (snitin315) [reply packages/webpack-cli/lib/groups/resolveConfig.js:184]: Thanks.

File: packages/webpack-cli/lib/groups/resolveConfig.js [hunk 6]
```diff
@@ -172,7 +174,15 @@ const finalize = async (moduleObj, args) => {
 
             return rawConfig;
         }),
-    );
+    ).then((allConfigs) => {
```
Comment (evilebottnawi) [inline packages/webpack-cli/lib/groups/resolveConfig.js:177]: Avoid using `then`, we can use `async`/`await` safely, I think we need eslint rule for this

**Review by evilebottnawi — COMMENTED** [review]
Anyway good job, thanks!

**Review by evilebottnawi — COMMENTED** [review]
Let's fix tests and we can merge

**Comment by snitin315** [comment]
Green CI 😄

**Review by rishabh3112 — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team
