### PR TITLE
fix(migrate): move options to use

### LINKED ISSUE #159: [Migrate] loaders transform: should options be always grouped with the loader
**Do you want to request a *feature* or report a *bug*?**
Bug/Question?

**What is the current behavior?**

This:

```
     {
        test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: 'static/media/[name].[hash:8].[ext]'
        }
      },
```

will be converted to this:

```
      {
        test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        use: [{
          loader: 'url-loader'
        }],
        options: {
          limit: 10000,
          name: 'static/media/[name].[hash:8].[ext]'
        }
      },
```

Question is: is this correct result or should options be grouped with the `loader`?

cc @sokra

### PR DESCRIPTION
**Pull request by sendilkumarn**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
NA

**Summary**
Fixes #159 

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

File: lib/migrate/loaders/loaders.js [hunk 1]
```diff
@@ -319,13 +319,59 @@ module.exports = function(j, ast) {
...
+	 *
+	 * Puts options object outside use object into use object
+	 *
+	 * @param {Node} p - object expression ast that has a key for either 'options' or 'use'
+	 * @returns {Node} objectExpression - an use object expression ast containing the options and loader
+	 */
+
+	const fitOptionsToUse = p => {
+		let options;
+		p.value.properties.map(prop => {
```
Comment (ematipico) [inline lib/migrate/loaders/loaders.js]: `.map` returns a new array. If you don't assign it, it's better to use `.forEach`.

File: lib/migrate/loaders/loaders.js [hunk 2]
```diff
@@ -319,13 +319,59 @@ module.exports = function(j, ast) {
...
+				options = prop;
+			}
+		});
+
+		if (options) {
+			p.value.properties = p.value.properties.filter(
+				prop => prop.key.name !== "options"
+			);
+
+			p.value.properties.map(prop => {
```
Comment (ematipico) [inline lib/migrate/loaders/loaders.js]: Also here: `.forEach` is more appropriate
